name: Generate and upload an rss feed for today's poem

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # run at 2 AM UTC

jobs:
  nightly:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rss
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Set up locales
        run: |
          sudo locale-gen es_ES.UTF-8
          sudo update-locale LANG=es_ES.UTF-8
      - name: Install dependencies
        run: python -m pip install -r requirements/app.txt --upgrade pip
      - name: Download db
        env:
          DL_URL: ${{secrets.DB_DL_URL}}
          DL_USER: ${{secrets.DB_DL_USER}}
          DL_PASSWD: ${{secrets.DB_DL_PASSWD}}
        run: curl -u "${DL_USER}:${DL_PASSWD}" --output poems.db ${DL_URL}
      - name: Generate poem rss file
        run: python -m poemadeldia poems.db > poemtest.xml
      - name: Upload poem rss file
        env:
          UL_URL: ${{secrets.RSS_UL_URL}}
          UL_USER: ${{secrets.RSS_UL_USER}}
          UL_PASSWD: ${{secrets.RSS_UL_PASSWD}}
        run: curl -T poemtest.xml  ${UL_URL} --user ${UL_USER}:${UL_PASSWD}

